fix(actions): don't use a singleton method for monkeypatching ScriptThingActions
boc-tothefuture/openhab-jruby pull request #614
Opened 2022-07-03 23:11 UTC by ccutrer

fixes #596

2022-07-08 11:18 UTC, jimtng requested changes
This would work for both openhab 3.3 and earlier

```ruby
      module Actions
        begin
          # openHAB 3.3 uses ScriptThingActionsImpl
          java_import Java::OrgOpenhabCoreAutomationModuleScriptInternalDefaultscope::ScriptThingActionsImpl
          ScriptThingActionsClass = ScriptThingActionsImpl
        rescue NameError
          # openHAB 3.2 uses ScriptThingActions
          java_import Java::OrgOpenhabCoreAutomationModuleScriptInternalDefaultscope::ScriptThingActions
          ScriptThingActionsClass = ScriptThingActions
        end
        #
        # MonkeyPatching ScriptThingActions
        #
        class ScriptThingActionsClass
          field_reader :THING_ACTIONS_MAP

          #
          # Fetch keys for all actions defined in OpenHAB
          #
          # @return [Set] of keys for defined actions in the form of 'scope-thing_uid'
          #
          def action_keys
            self.class.THING_ACTIONS_MAP.keys
          end
        end
      end
```

2022-07-11 03:37 UTC, ccutrer commented
> This would work for both openhab 3.3 and earlier

done

2022-07-11 04:26 UTC, jimtng approved these changes

2022-07-22 22:02 UTC, jimtng commented
@ccutrer there's a merge conflict now

2022-07-25 22:14 UTC, merged